### ISSUE TITLE
Only the first noise volume appears to be used

### ISSUE THREAD

**Issue by tsalo** [SteenMoeller/NORDIC_Raw#22]
https://github.com/SteenMoeller/NORDIC_Raw/blob/ba924a391e91f4ba9a5f9058ad32362f0315160b/NIFTI_NORDIC.m#L487-L489

In the above, I believe `KSP2_NOISE` is only created from the first noise volume, rather than all of them. Should it instead be the following?

```matlab
 if ARG.noise_volume_last>0 
     KSP2_NOISE =KSP2(:,:,:,end+1-ARG.noise_volume_last:end); 
 end 
```

**Comment by SteenMoeller** [comment]
It should not make a difference if the noise is the same. Only the variance from the noise is used. One volume should be sufficient. One can extend it to all volumes, but since there is no default option for having these volumes there could be a case where different "types" of noise volumes are used. E.g. including or excluding various levels of hardware. It would not wrong to use all volumes, but it would also not be better.
